name: data-analyst-mayo-2026
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - jupyterlab
  - notebook
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - statsmodels
  - plotly
  - seaborn
